image:
  file: Dockerfile.gitpod

ports:
  # symofny
  - port: 8000
  # storybook
  - port: 6006
  # mailhog web interface
  - port: 8025
    onOpen: notify
  # mailhog postfix
  - port: 1025
    onOpen: ignore
  # openldap
  - port: 10389
    onOpen: ignore
  # openldap (SSL)
  - port: 10636
    onOpen: ignore

tasks:
  # https://github.com/gitpod-io/gitpod/issues/666#issuecomment-534347856
  - before: >
      [[ ! -z ${GNUGPG}  ]] &&
      cd ~ &&
      rm -rf .gnupg &&
      echo ${GNUGPG} | base64 -d | tar --no-same-owner -xzvf -
    name: signed terminal
    init: >
      [[ ! -z ${GNUGPG_KEY}  ]] &&
      git config --global commit.gpgsign true &&
      git config --global user.signingkey ${GNUGPG_KEY}
    command: >
      cd $GITPOD_REPO_ROOT &&
      ./manage.sh
  - init: ./manage.sh local:build
    name: backend
    command: >
      gp sync-done 'backend-init' &&
      ./manage.sh local:start-back --no-interaction
  - name: frontend
    command: >
      gp sync-await 'backend-init' &&
      ./manage.sh local:start-front
  - name: storybook
    command: >
      gp sync-await 'backend-init' &&
      gp await-port 8000 &&
      ./manage.sh local:start-story
  #- name: openldap
  #  command: >
  #    /usr/bin/tini -- /usr/sbin/slapd -h ldapi:/// ldap://0.0.0.0:10389 ldaps://0.0.0.0:10636 -d 256
  #- before: go get github.com/mailhog/MailHog
  #  name: mailhog
  #  openMode: split-right
  #  command: MailHog

vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==

    - felixfbecker.php-pack@1.0.2:2V0NCoZNF9GELURKXgdHeQ==

    - syler.sass-indented@1.8.15:OWaLl5oCHRK7fCfvhwK3og==

    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==

    - octref.vetur@0.32.0:03mwRhlVpWDul4qBChcVUA==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
