os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - export VCS_REF=$(git rev-parse --short HEAD)
  - export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - export DOCKER_TAG=${VERSION}-${VARIANT}-travis
  - export DOCKER_REPO=monogramm/vue-symfony-starter
  - export DOCKERFILE_PATH=Dockerfile.${VARIANT}
  - export DOCKER_TAG=${VARIANT}
  - export IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}

install:
  # Build project
  - ./hooks/build

before_script:
  - docker images

script:
  # Execute project CI Tests
  - ./hooks/pre_test
  - ./hooks/test
  - ./hooks/post_test

notifications:
  email: false

matrix:
  allow_failures:
    - env: VARIANT=debian BASE=fpm

env: # Environments
    - VARIANT=alpine BASE=fpm
    - VARIANT=debian BASE=fpm
    #- VARIANT=fpm-alpine BASE=fpm
    #- VARIANT=fpm BASE=fpm
    #- VARIANT=apache BASE=apache
