{
 "title": "Erlang-Distributions-Compare",
 "tags": [
  "cadvisor",
  "node-exporter",
  "rabbitmq-perf-test",
  "rabbitmq-prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info, rabbitmq_cluster)"
    }
   },
   {
    "name": "instance",
    "label": "PerfTest Instance",
    "query": {
     "query": "label_values(perftest_published, instance)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": {
     "query": "label_values(perftest_latency_seconds, quantile)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_network_info, instance)"
    }
   },
   {
    "name": "container",
    "label": "or Container",
    "query": {
     "query": "label_values(container_network_receive_bytes_total, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "rabbitmq-prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Erlang Distribution outgoing traffic / s",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_send_bytes[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\"}",
     "legendFormat": "{{rabbitmq_node}} -> {{peer}}"
    }
   ]
  },
  {
   "title": "Erlang Distribution outgoing traffic / s",
   "type": "graph",
   "description": "Erlang Distribution traffic, node network traffic and CPU + PerfTest message throughput and latency",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_send_bytes[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\"}",
     "legendFormat": "{{rabbitmq_node}} -> {{peer}}"
    }
   ]
  },
  { "title": "node-exporter_cadvisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network incoming traffic / s",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{name=~\"$container\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network incoming traffic / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{name=~\"$container\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network outgoing traffic / s",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{name=~\"$container\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network outgoing traffic / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{name=~\"$container\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(max by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=~\"user|system|iowait|softirq\", instance=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (irate(container_cpu_usage_seconds_total{name=~\"$container\"}[1m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(max by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=~\"user|system|iowait|softirq\", instance=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (irate(container_cpu_usage_seconds_total{name=~\"$container\"}[1m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}