
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['debian', 'alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_build
        run: |
          export EXPORT_TESTS_RESULTS=true
          ./hooks/run ${{ matrix.variant }} 'fpm'
          ls -al . ./.docker ./.docker/app ./.docker/app/.docker

      - name: Display docker images
        run: docker images

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: .docker/app/.docker/tests-coverage-clover.xml
