
name: Docker Image CI

on:
  pull_request:
  push:
    #branches:
    #  - master
    #  - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_build
        run: |
          export EXPORT_TESTS_RESULTS=true
          ./hooks/run ${{ matrix.variant }} 'fpm'

      - name: Display docker images
        run: docker images

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .docker/app/html/.docker/tests-coverage-clover.xml
          base-path: ./app
