
name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_build
        run: |
          ./hooks/run ${{ matrix.variant }} 'fpm'

      - name: Display docker images
        run: docker images
